version: '3'
services:

  api:
    image: golang:1.15
    container_name: api
    ports:
      - 8000:8000
    volumes:
      - ./:/worker
    working_dir: /worker/exec
    command: go run .

  converter:
    image: golang:1.15
    container_name: converter
    volumes:
      - ./:/worker
    working_dir: /worker/exec/converter
    command: go run .
